version: '3'

services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      REDIS_URL: ${REDIS_URL}
    env_file:
      - .env
    volumes:
      - mysql-data-volume:/var/lib/mysql

  redis:
    image: redis
    environment:
      REDIS_URL: ${REDIS_URL}

  backend:
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3001:3000'
    environment:
      CHOKIDAR_USEPOLLING: true
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
      REACT_APP_BACKEND_CABLE_URL: ${REACT_APP_BACKEND_CABLE_URL}
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  mysql-data-volume:
    external: true
