version: '3'

services:
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
    env_file:
      - .env
    volumes:
      - mysql-data-volume:/var/lib/mysql

  redis:
    image: redis
    environment:
      - REDIS_URL=redis://redis:6379

  api:
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3001:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
    env_file:
      - .env
    depends_on:
      - api

volumes:
  mysql-data-volume:
    external: true
