version: '3'

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    volumes:
      - mysql-data-volume:/var/lib/mysql

  api:
    build: ./backend
    command: bash -c "bundle install && rake db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3001:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    depends_on:
      - api


volumes:
  mysql-data-volume:
    external: true
