name: Auto deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMITANO_VPS_HOST }}
          username: ${{ secrets.REMITANO_VPS_USERNAME }}
          password: ${{ secrets.REMITANO_VPS_PASSWORD }}
          script: |
            cd Remitano-Test/
            git pull origin master
            sudo docker compose -f docker-compose.prod.yml down
            sudo docker compose -f docker-compose.prod.yml build
            sudo docker compose -f docker-compose.prod.yml up -d
